### ISSUE TITLE
DataFrameError: The DataFrame you passed does not contain data

### ISSUE THREAD

**Issue by AchimTack** [duarteocarmo/think-cell#4] opened 2020-09-04 14:17 UTC
Thanks for this great project, I really appreciate your time and effort!

Maybe a stupid question but I'm stuck figuring out the correct df-format for a relatively simple barchart:
![image](https://user-images.githubusercontent.com/20294926/92248620-444dad80-eec9-11ea-9393-0e4c5ff79dcf.png)

Thinkcell requires this excel-format:
![image](https://user-images.githubusercontent.com/20294926/92248729-65160300-eec9-11ea-9732-0139e284bdcc.png)

My df ist structured in this way:
```<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   ha       10 non-null     object 
 1   percent  10 non-null     float64
dtypes: float64(1), object(1)
```

I tried severaly ways of reformatting the df but failed. Any suggestions would be highly welcomed.

UPDATE: 
It sort-of works if I add an empty "data" column between "ha" an "percent". It appears to be an Issue with the script not expecting single-column charts.

**Comment by duarteocarmo** [comment] 2020-09-04 15:43
Hey! This feature was implemented by @rebost (@eisams) so I'm sure he can provide you with a bit more input on what is wrong here 😄 

Thanks for reaching out!

**Comment by matias-pizarro** [comment] 2020-09-14 14:44
Hey Achim. Can you provide me with a basic, or no so basic, way to reproduce the error?
Ideally a dummy df and a script which showcases the error?

**Comment by duarteocarmo** [comment] 2020-09-17 14:23
@AchimTack closing this due to inactivity, do let me know if we can help in case this persists!

**Comment by boukepostma** [comment] 2021-08-18 16:21
Hi guys! First of all: thanks for the great work developing this package! 

I'm running into the same issue when trying to add a chart with only one category (e.g. a single bar plot with 3 bars). 

Basic example:
```
import pandas as pd
from thinkcell import Thinkcell

TEMPLATE_NAME = 'template.pptx'
tc = Thinkcell()
tc.add_template(TEMPLATE_NAME)

df = pd.DataFrame({"series_name":["a","b","c"], "value":[1,2,3]})
tc.add_chart_from_dataframe(
        template_name=TEMPLATE_NAME,
        chart_name = "name",
        dataframe = df,
    )
```

This results in the following DataframeError:
![image](https://user-images.githubusercontent.com/33422940/129934777-90c11661-3cb5-49e0-9af4-dfc19eba2b4c.png)

Would it be possible to simply loosen this assert statement to the following, or does the rest of the code fail when adding a graph with only one category?
```
assert len(categories) >= 1
```

Thanks!!

**Comment by duarteocarmo** [comment] 2021-08-18 16:23
@boukepostma  - I don't see an issue with your proposal! Do you want to perhaps send a pull request in? Happy to make another release once that's merged :)

**Comment by boukepostma** [comment] 2021-08-18 17:17
Awesome! I'll send in a pull request somewhere during the next days.

**Comment by boukepostma** [comment] 2021-09-08 10:21
Sorry for the delayed response. I see that @colegrigsby already solved this in his latest pull request. So this issue can be closed!

Thanks for the great work guys :)

**Closed as completed** 2021-09-08 10:27 UTC
